import "./globals.css";
import { Analytics } from "@vercel/analytics/react";

export const metadata = {
  title: "Brayan Amaral - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <Analytics />
      <body className="bg-slate-900 leading-relaxed text-slate-400 antialiased selection:bg-teal-300 selection:text-teal-900">
        {children}
      </body>
    </html>
  );
}
